WebApplication1/WebApplication1/ViewModels/AutorisationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BSTeamSearch.Models;

namespace BSTeamSearch.ViewModels
{
    public class AutorisationViewModel
    {
        [Required(ErrorMessage = "Поле логгин не может быть пустым")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Поле пароля не может быть пустым")]
        public string Password { get; set; }
    }
}

WebApplication1/WebApplication1/Controllers/AutorisationController.cs
using BSTeamSearch.DataBase;
using BSTeamSearch.Models;
using BSTeamSearch.Repositories.Interfaces;
using BSTeamSearch.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BSTeamSearch.Controllers
{
    public class AutorisationController : Controller
    {
        private readonly IUserRepository _userRepository;
        public AutorisationController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult AutorisationToTheSite()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AutorisationToTheSite(AutorisationViewModel user)
        {
            if (!(user.Name is null || user.Password is null) &&
               (!_userRepository.UserIsRegistered(user.Name) ||
               !_userRepository.PasswordIsCorrect(user.Name, user.Password)))
            {
                ModelState.AddModelError("Password", "Логгин или пароль указаны неправильно");
            }

            if (_userRepository.UserIsRegistered(user.Name) && _userRepository.Get(user.Name).IsBanned)
            {
                ModelState.AddModelError("Name", "Ваш аккаунт забанен");
            }

            if (ModelState.IsValid)
            {
                ControllerContext.HttpContext.Session.SetString("name", user.Name);
                if (_userRepository.Get(user.Name).IsAdmin)
                {
                    return RedirectPermanent("../Admin/Index");
                }

                ViewBag.UserName = user.Name;
                return RedirectPermanent("../Applications/All");
            }

            return View(user);
        }
    }
}

WebApplication1/WebApplication1/Views/Autorisation/AutorisationToTheSite.cshtml
@{
    Layout = null;
}
@model AutorisationViewModel


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/nullStyle.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/autorisation.css" rel="stylesheet" />
    <title>Вход</title>
    <script src="@Url.Content("~/scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
</head>
<body>
    <div class="container">
        <div class="autorisation">
            <div class="autorisation__content">
                <div class="autorisation__content__title"><span class="text2">Вход</span></div>
                <div class="autorisation__content__form">
                    <form asp-action="AutorisationToTheSite" asp-controller="Autorisation" asp-antiforgery="true">
                            <p class="text3 text_marg autorisation__input__label">Ваш логин:</p>
                            <input class="autorisation__input" asp-for="Name" type="text">
                            <span asp-validation-for="Name"></span>
                            <p class="text3 text_marg autorisation__input__label">Ваш пароль:</p>
                            <input class="autorisation__input" asp-for="Password" type="password"/>
                            <span asp-validation-for="Password" data-valmsg-for=Password
                                data-valmsg-replace="true"></span>
                            <input class="text1 text_marg autorisation__submit" type="submit" value="Войти" />
                    </form>
                    <div class="text3 autorisation__content__text">
                        <span>Еще нет аккаунта?</span>
                        <a href="../Registration/Registration" class="autorisation__content__link">Регистрация</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>