WebApplication1/WebApplication1/Models/Application.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BSTeamSearch.Models
{
    public class Application
    {
        [Key]
        public int Id { get; set; }

        public int CountOfCups { get; set; }

        public string UserName { get; set; }
        public User User { get; set; }

        public string BrawlerName { get; set; }
        public Brawler Brawler { get; set; }

        public bool HasVoiceChat { get; set; }

        public string Description { get; set; }

        public List<Like> Likes { get; set; }

        public Application(int countOfCups, string userName, string brawlerName, bool hasVoiceChat, string description)
        {
            CountOfCups = countOfCups;
            UserName = userName;
            BrawlerName = brawlerName;
            HasVoiceChat = hasVoiceChat;
            Description = description;
        }
    }
}

WebApplication1/WebApplication1/Controllers/ApplicationsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using BSTeamSearch.Exceptions;
using BSTeamSearch.Models;
using BSTeamSearch.Repositories.Interfaces;
using BSTeamSearch.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BSTeamSearch.Controllers
{
    public class ApplicationsController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IApplicationRepository _applicationRepository;
        private readonly IBrawlerRepository _brawlerRepository;

        public ApplicationsController(IApplicationRepository applicationRepository, IUserRepository userRepository, IBrawlerRepository brawlerRepository )
        {
            _userRepository = userRepository;
            _applicationRepository = applicationRepository;
            _brawlerRepository = brawlerRepository;
        }

        public IActionResult All()
        {
            var userName = ControllerContext.HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return View("../NotRegistered");
            }

            ViewBag.UserName = userName;
            var applicationList = _applicationRepository.GetAllWithout(userName);
            return View(applicationList);
        }

        public IActionResult Edit(int id)
        {
            ViewBag.UserName = ControllerContext.HttpContext.Session.GetString("name");
            if (ViewBag.UserName is null || !_userRepository.UserIsRegistered(ViewBag.UserName))
            {
                return View("../NotRegistered");
            }

            Application application;
            try
            {
                application = _applicationRepository.Get(id);
            }
            catch
            {
                return Redirect("../Applications/All");
            }

            if (!_applicationRepository.GetUserApplications((string)ViewBag.UserName).Contains(application))
            {
                return Redirect("../Applications/All");
            }

            ViewBag.Brawlers = _brawlerRepository.GetAll();
            return View(ApplicationEditViewModel.GetViewModel(application));
        }

        [HttpPost]
        public IActionResult Edit(ApplicationEditViewModel application)
        {
            ViewBag.UserName = ControllerContext.HttpContext.Session.GetString("name");
            if (ViewBag.UserName is null || !_userRepository.UserIsRegistered(ViewBag.UserName))
            {
                return View("../NotRegistered");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.Brawlers = _brawlerRepository.GetAll();
                return View(application);
            }

            Application editingApplication;
            try
            {
                editingApplication = _applicationRepository.Get(application.Id);
            }
            catch
            {
                return Redirect("../Applications/All");
            }

            if (!_applicationRepository.GetUserApplications((string)ViewBag.UserName).Contains(editingApplication))
            {
                return Redirect("../Applications/All");
            }

            _applicationRepository.Edit(application.GetApplicationModel(ViewBag.UserName));
            return Redirect("../Applications/My");
        }

        public IActionResult Add()
        {
            var userName = ControllerContext.HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return View("../NotRegistered");
            }

            ViewBag.Brawlers = _brawlerRepository.GetAll();

            ViewBag.UserName = userName;
            return View();
        }

        [HttpPost]
        public IActionResult Add(ApplicationAddViewModel application)
        {
            var userName = ControllerContext.HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return View("../NotRegistered");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.Brawlers = _brawlerRepository.GetAll();
                return View(application);
            }

            ViewBag.UserName = userName;
            _applicationRepository.Add(application.GetApplicationModel(userName));

            return RedirectPermanent("../Applications/All");
        }

        public IActionResult My()
        {
            var userName = ControllerContext.HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return View("../NotRegistered");
            }

            IEnumerable userApplications;
            ViewBag.UserName = userName;
            try
            {
                userApplications = _applicationRepository.GetUserApplications(userName);
            }
            catch (ObjectNotFoundInDataBaseException)
            {
                return View(null);
            }

            return View(userApplications);
        }

        [HttpPost]
        public bool Delete(int applicationId)
        {
            var userName = HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return false;
            }

            try
            {
                _applicationRepository.Delete(_applicationRepository.Get(applicationId), userName);
            }
            catch
            {
                return false;
            }

            return true;
        }

        [HttpPost]
        public IActionResult Filtration(bool onlyLiked, bool cupsAscending, string searchString, int minCups, int maxCups)
        {
            var userName = ControllerContext.HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return View("../NotRegistered");
            }

            ViewBag.UserName = userName;
            var applicationList = _applicationRepository.FiltrationGet(userName, onlyLiked, cupsAscending, searchString, minCups, maxCups).ToList();

            return View(applicationList);
        }
    }
}

WebApplication1/WebApplication1/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BSTeamSearch.Models;
using BSTeamSearch.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BSTeamSearch.Controllers
{
    public class ChatController : Controller
    {
        private readonly IGroupRepository _groupRepository;
        private readonly IUserRepository _userRepository;
        public ChatController(IGroupRepository groupRepository, IUserRepository userRepository)
        {
            _groupRepository = groupRepository;
            _userRepository = userRepository;
        }

        public IActionResult Index()
        {
            var userName = HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return Redirect("../NotRegistered");
            }

            var groups = _groupRepository.GetGroupsForUser(userName);
            ViewBag.UserName = userName;
            return View(groups);
        }

        [HttpGet]
        public IActionResult SendMessage(string toUser)
        {
            string userName = HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return Redirect("../NotRegistered");
            }

            ViewBag.UserName = userName;
            if (userName == toUser || !_userRepository.UserIsRegistered(toUser))
            {
                return View("../Chat/Index", _groupRepository.GetGroupsForUser(userName));
            }

            if (!_groupRepository.GroupIsCreated(userName, toUser))
            {
                _groupRepository.CreateGroup(userName, toUser);
            }

            ViewBag.CurrentChat = _groupRepository.GetGroup(userName, toUser);
            return View("../Chat/Index", _groupRepository.GetGroupsForUser(userName));
        }

        [HttpPost]
        public IActionResult GetChat(int chatId)
        {
            var userName = HttpContext.Session.GetString("name");
            if (userName is null || !_userRepository.UserIsRegistered(userName))
            {
                return Redirect("../NotRegistered");
            }

            if (!_groupRepository.GroupIsCreated(chatId))
            {
                return null;
            }

            ViewBag.UserName = userName;
            return View(_groupRepository.GetGroup(chatId));
        }
    }
}

WebApplication1/WebApplication1/Views/Applications/Add.cshtml
@{
    Layout = "_MainLayout";
}
@model ApplicationAddViewModel
    <link href="~/css/add.css" rel="stylesheet" />
<div class="add">
    <div class="add__content">
        <div class="add__content__title"><span class="text2">Создание заявки</span></div>
        <div class="add__content__form">
            <form asp-action="Add" asp-controller="Applications" method="post">
                <p class="text3 add__input__label">Выберите бравлера:</p>
                <select asp-for="BrawlerName">
                    @{
                        foreach (Brawler elem in ViewBag.Brawlers)
                        {
                            <option>@elem.Name</option>
                        }
                    }
                </select>
                <p class="text3 add__input__label">Выберите количество кубков:</p>
                <input type="number" required asp-for="CountOfCups" />
                <span asp-validation-for="CountOfCups"></span>
                <p class="text3 add__input__label">Есть ли у вас возможость общаться по голосовому чату?</p>
                <select asp-for="HasVoiceChat">
                    <option value="false">Нет</option>
                    <option value="true">Да</option>
                </select>
                <p class="text3 add__input__label">Напишите пару слов о себе и о данной заявке</p>
                <textarea type="text" asp-for="Description" placeholder="например в каком режиме хотите играть, в какоевремя вам удобно играть"></textarea>
                <span asp-validation-for="Description"></span>
                <input class="add__submit" type="submit" value="Отправить" />
            </form>
        </div>
    </div>
</div>

WebApplication1/WebApplication1/Views/Applications/All.cshtml
@{
    Layout = "_MainLayout";
}
@model List<Application>
     <div class="search">
    <div class="text2 application__title">Просмотр заявок</div>
    <div class="filtration_params">
        <div class="content__search__rangeCost">
            <div class="content__search__rangeCost__values">
                <span class="text3">Кубки от</span>
                <span class="text3" id="content__search__rangeCost__range1">0</span>
                <span class="text3">Кубки до </span>
                <span class="text3" id="content__search__rangeCost__range2">1250</span>
            </div>
            <div class="content__search__rangeCost__container">
                <div class="slider-track"></div>
                <input name="minCups" type="range" min="0" max="1250" value="0" id="slider-1" oninput="slideOne()">
                <input name="maxCups" type="range" min="0" max="1250" value="1250" id="slider-2" oninput="slideTwo()">
            </div>
        </div>
        <div class="filtration_params__select">
            <span class="text3">Только лайкнутые</span>
            <select class="text3" id="onlyLiked">
                <option value="false">нет</option>
                <option value="true">да</option>
            </select>
            <select class="text3" id="cupsAscending">
                <option value="true">кубки по возрастанию</option>
                <option value="false">кубки по убыванию</option>
            </select>
        </div>
        <div class="filtration_params__input">
            <input type="text" class="text3" id="application__searchString" />
            <input type="button" class="text3" name="Поиск" value="Поиск" onclick="submitParams('/Applications/Filtration')" />
        </div>
    </div>
</div>
        <script src="~/js/slider.js"></script>
        <script src="~/js/sendFiltrationParams.js"></script>
        <link href="~/css/search.css" rel="stylesheet" />
        <link href="~/css/application.css" rel="stylesheet" />

         <div class="application">
        <div class="application__content">
    @if (Model is null || Model.Count == 0)
    {
        <div>
            <p class="text3">ничего не найдено</p>
        </div>
    }
    else
    {
<div class="application__content">
    
    @foreach (var elem in Model)
    {
        string countClass = "count" + elem.Id;
        string likeClass;
        string firstId = "first" + elem.Id;
        string secId = "second" + elem.Id;
        if (elem.Likes.FirstOrDefault(c => c.UserName == ViewBag.UserName) is null)
        {
            likeClass = "unliked";
        }
        else
        {
            likeClass = "liked";
        }
            <div class="application__item" id="@elem.Id">
                <div class="application__item__first">
                    <div class="application__item__photo">
                        <img height="150" width="150" src=@elem.Brawler.Img />
                    </div>
                    <div class="application__item__info">
                        <div class="text2 application__info__title">@elem.Brawler.Name</div>
                        <div class="text3 application__info__cup">Кубков: <span>@elem.CountOfCups</span></div>
                        <div class="text3 application__info__desc">@elem.Description</div>
                    </div>
                </div>
                <div class="application__item__control">
                    <div class="text3 application__control__name">@elem.UserName</div>
                    <div class="application__control__like">
                    <svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="50px" height="50px"
                        viewBox="0 0 256.000000 256.000000" preserveAspectRatio="xMidYMid meet"
                        onclick="Like(@elem.Id)">

                        <g transform="translate(0.000000,256.000000) scale(0.100000,-0.100000)" fill="#000000"
                            stroke="none">
                            <path class="@likeClass @firstId" d="M1045 2066 c-48 -18 -86 -60 -102 -115 -18 -57 -19 -1241 -1 -1259
                                    19 -19 824 -17 858 3 14 8 32 17 40 21 8 4 29 21 45 38 l30 31 3 301 3 302 36
                                    7 c45 8 93 57 104 105 5 19 9 61 9 92 0 54 -2 59 -49 110 l-49 53 -311 3 -311
                                    3 0 89 c0 49 -4 92 -10 95 -5 3 -10 14 -10 24 0 9 -20 37 -45 61 -43 43 -45
                                    43 -122 47 -52 2 -91 -2 -118 -11z" />
                            <path class="@likeClass @secId" d="M497 1753 c-4 -3 -7 -239 -7 -524 0 -457 2 -519 16 -533 12 -13 41
                                    -16 153 -16 121 0 140 2 154 18 15 17 17 68 17 528 0 383 -3 513 -12 522 -13
                                    13 -309 18 -321 5z" />
                        </g>
                    </svg>
                    <span class="text2 @countClass">@elem.Likes.Count</span>
                    </div>
                    <a asp-action="SendMessage" asp-controller="Chat" asp-route-toUser="@elem.UserName"
                        class="text3 application__control__button">Отправить сообщение</a>
                </div>
            </div>
    }
</div>
    }
        </div>
    </div>

WebApplication1/WebApplication1/Views/Applications/Edit.cshtml
@{
    Layout = "_MainLayout";
}
@model ApplicationEditViewModel
<link href="~/css/add.css" rel="stylesheet" />
<div class="add">
    <div class="add__content">
        <div class="add__content__title"><span class="text2">Редактирование заявки</span></div>
        <div class="add__content__form">
            <form asp-action="Edit" asp-controller="Applications" method="post">
                <p class="text3 text_marg add__input__label">Выберите бравлера:</p>
                <select asp-for="BrawlerName">
                    @{
                        var ap = Model;
                        foreach (Brawler elem in ViewBag.Brawlers)
                        {
                            <option>@elem.Name</option>
                        }
                    }
                </select>
                <p class="text3 text_marg add__input__label">Выберите количество кубков:</p>
                <input type="number" required asp-for="CountOfCups" />
                <span asp-validation-for="CountOfCups"></span>
                <p class="text3 text_marg add__input__label">Есть ли у вас возможость общаться по голосовому чату?</p>
                <select asp-for="HasVoiceChat">
                    <option value="false">Нет</option>
                    <option value="true">Да</option>
                </select>
                <p class="text3 text_marg add__input__label">Напишите пару слов о себе и о данной заявке</p>
                <textarea type="text" asp-for="Description" placeholder="например в каком режиме хотите играть, в какоевремя вам удобно играть"></textarea>
                <span asp-validation-for="Description"></span>
                <input type="number" asp-for="Id" value="@Model.Id" style="display:none;"/>
                <input class="add__submit text_marg" type="submit" value="Отправить" />
            </form>
        </div>
    </div>
</div>

WebApplication1/WebApplication1/Views/Applications/Filtration.cshtml
@{
    Layout = null;
}
@model List<Application>
@{
    if (Model is null || Model.Count == 0)
    {
        <div>
            <p class="text3">ничего не найдено</p>
        </div>
    }
    else
    {
     <div class="application__content">
    
    @foreach (var elem in Model)
    {
        string countClass = "count" + elem.Id;
        string likeClass;
        string firstId = "first" + elem.Id;
        string secId = "second" + elem.Id;
        if (elem.Likes.FirstOrDefault(c => c.UserName == ViewBag.UserName) is null)
        {
            likeClass = "unliked";
        }
        else
        {
            likeClass = "liked";
        }
            <div class="application__item" id="@elem.Id">
                <div class="application__item__first">
                    <div class="application__item__photo">
                        <img height="150" width="150" src=@elem.Brawler.Img />
                    </div>
                    <div class="application__item__info">
                        <div class="text2 application__info__title">@elem.Brawler.Name</div>
                        <div class="text3 application__info__cup">Кубков: <span>@elem.CountOfCups</span></div>
                        <div class="text3 application__info__desc">@elem.Description</div>
                    </div>
                </div>
                <div class="application__item__control">
                    <div class="text3 application__control__name">@elem.UserName</div>
                    <div class="application__control__like">
                    <svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="50px" height="50px"
                        viewBox="0 0 256.000000 256.000000" preserveAspectRatio="xMidYMid meet"
                        onclick="Like(@elem.Id)">

                        <g transform="translate(0.000000,256.000000) scale(0.100000,-0.100000)" fill="#000000"
                            stroke="none">
                            <path class="@likeClass @firstId" d="M1045 2066 c-48 -18 -86 -60 -102 -115 -18 -57 -19 -1241 -1 -1259
                                    19 -19 824 -17 858 3 14 8 32 17 40 21 8 4 29 21 45 38 l30 31 3 301 3 302 36
                                    7 c45 8 93 57 104 105 5 19 9 61 9 92 0 54 -2 59 -49 110 l-49 53 -311 3 -311
                                    3 0 89 c0 49 -4 92 -10 95 -5 3 -10 14 -10 24 0 9 -20 37 -45 61 -43 43 -45
                                    43 -122 47 -52 2 -91 -2 -118 -11z" />
                            <path class="@likeClass @secId" d="M497 1753 c-4 -3 -7 -239 -7 -524 0 -457 2 -519 16 -533 12 -13 41
                                    -16 153 -16 121 0 140 2 154 18 15 17 17 68 17 528 0 383 -3 513 -12 522 -13
                                    13 -309 18 -321 5z" />
                        </g>
                    </svg>
                    <span class="text2 @countClass">@elem.Likes.Count</span>
                    </div>
                    <a asp-action="SendMessage" asp-controller="Chat" asp-route-toUser="@elem.UserName"
                        class="text3 application__control__button">Отправить сообщение</a>
                </div>
            </div>
    }
</div>
        }
    }

WebApplication1/WebApplication1/Views/Applications/My.cshtml
@{
    Layout = "_MainLayout";
}
@model IEnumerable<Application>

<link href="~/css/application.css" rel="stylesheet" />
<div class="application">
        <div class="application__content">
    @if (Model is null)
    {
        <div>
            <p class="text2">Покачто нет заявок</p>
        </div>
    }
    else
    {
            @foreach (var elem in Model)
            {
            <div class="application__item" id="@elem.Id">
                <div class="application__item__first">
                    <div class="application__item__photo">
                        <img height="150" width="150" src=@elem.Brawler.Img />
                    </div>
                    <div class="application__item__info">
                        <div class="text2 application__info__title">@elem.Brawler.Name</div>
                        <div class="text3 application__info__cup">Кубков: <span>@elem.CountOfCups</span></div>
                        <div class="text3 application__info__desc">@elem.Description</div>
                        
                    </div>
                </div>
                <div class="application__item__control">
                    <div class="text3 application__control__name">@elem.User.Name</div>
                    <a asp-action="Edit" asp-controller="Applications" asp-route-id="@elem.Id" class="text3 application__edit__button">Редактировать</a>
                    <button class="text3 application__control__button">Удалить</button>
                    <button class="text3 application__control__button__delete"
                            onclick="deleteApplication(@elem.Id)">
                        Удалить
                    </button>
                </div>
            </div>
            }
        <script src="~/js/deleteApplication.js"></script>
    }
            </div>
    </div>